### ISSUE TITLE
Good website

### ISSUE THREAD

**Issue by KirboIs1337** [GavinGamesReboot/GavinsGamesV2#1]
Good!

**Comment by caldwellchris** [comment]
@KirboIs1337 Help me understand. Are you experiencing issues when cloning this locally? Does the documentation need to be improved?

**Comment by KirboIs1337** [comment]
Sorry for being a dummy! I have closed this so no more trouble can be caused, this website is very good and little needs to be improved onto! Sorry if I have wasted your time!
